import "./globals.css";

import type { Metadata } from "next";
import { Nixie_One } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";

const nixieOne = Nixie_One({
  variable: "--font-nixie-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Prainha Café",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${nixieOne.variable}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
